<?php

return [
    'ciphers' => [
        'english_gematria' => 'English Gematria',
        'simple_gematria' => 'Simple',
        'unknown_gematria' => 'Unknown',
        'pythagoras_gematria' => 'Pythagoras',
        'jewish_gematria' => 'Jewish',
        'prime_gematria' => 'Prime',
        'reverse_satanic_gematria' => 'Reverse Satanic',
        'clock_gematria' => 'Clock',
        'reverse_clock_gematria' => 'Reverse Clock',
        'system9_gematria' => 'System 9',
        'francis_bacon_gematria' => 'Francis Bacon',
        'septenary_gematria' => 'Septenary',
        'glyph_geometry_gematria' => 'Glyph Geometry',
    ],
    'default_enabled' => [
        'english_gematria',
        'simple_gematria',
        'jewish_gematria',
        'prime_gematria',
        'reverse_satanic_gematria',
        'clock_gematria',
        'reverse_clock_gematria',
        'system9_gematria',
    ],
    'descriptions' => [
        'english_gematria' => 'A=6, B=12 ... Z=156. Each letter is six times its alphabet index.',
        'simple_gematria' => 'Classic alphabetical mapping: A=1 ... Z=26.',
        'unknown_gematria' => 'Offset mapping: A=99 ... Z=124.',
        'pythagoras_gematria' => 'Specific mapping based on the reference file (including master numbers 11 and 22).',
        'jewish_gematria' => 'Jewish mapping with expanded values (for example J=600, V=700, W=900).',
        'prime_gematria' => 'A=2, B=3, C=5 ... Z=101 (prime sequence).',
        'reverse_satanic_gematria' => 'Reverse-Satanic: A=61 ... Z=36.',
        'clock_gematria' => '12-cycle mapping: A=1 ... L=12, M=1 ...',
        'reverse_clock_gematria' => 'Reverse 12-cycle mapping based on the reference.',
        'system9_gematria' => 'A=9, B=18 ... Z=234 (9-system).',
        'francis_bacon_gematria' => 'Bacon mapping with +26 offset: A=27 ... Z=52.',
        'septenary_gematria' => 'Symmetric 1-7-1 wave across the alphabet.',
        'glyph_geometry_gematria' => 'Visual glyph complexity based on straight lines, curves, and enclosed areas.',
    ],
    'details' => [
        'english_gematria' => [
            'short' => 'Alphabet index x 6',
            'formula' => 'Value(letter) = Position(A1..Z26) * 6',
            'method' => 'Linear multiplier. The distance between letters stays constant.',
            'example' => 'C(18) + O(90) + M(78) + P(96) + U(126) + T(120) + E(30) + R(108) = 666',
        ],
        'simple_gematria' => [
            'short' => 'A1 to Z26',
            'formula' => 'Value(letter) = Position(A1..Z26)',
            'method' => 'Classic ordinal gematria without multipliers or offsets.',
            'example' => 'COMPUTER = 3+15+13+16+21+20+5+18 = 111',
        ],
        'unknown_gematria' => [
            'short' => 'A99 to Z124',
            'formula' => 'Value(letter) = Position + 98',
            'method' => 'Constant offset on alphabet index. Relative distances are preserved while values shift upward.',
            'example' => 'A=99, B=100, ... Z=124',
        ],
        'pythagoras_gematria' => [
            'short' => 'Reference mapping',
            'formula' => 'Fixed mapping from the reference table',
            'method' => 'Non-linear; specific letters carry special values (including 11 and 22).',
            'example' => 'Values are read from a predefined table rather than derived linearly.',
        ],
        'jewish_gematria' => [
            'short' => 'Extended Jewish mapping',
            'formula' => 'A..I = 1..9, then expanded jumps',
            'method' => 'From J onward, larger jumps are used (for example J=600, V=700, W=900).',
            'example' => 'J=600, T=100, U=200, V=700, W=900',
        ],
        'prime_gematria' => [
            'short' => 'Prime sequence',
            'formula' => 'Value(letter) = n-th prime number',
            'method' => 'A=2, B=3, C=5 ... Z=101. Later letters spread apart faster than ordinal systems.',
            'example' => 'A=2, E=11, M=41, Z=101',
        ],
        'reverse_satanic_gematria' => [
            'short' => 'Reverse with offset',
            'formula' => 'Value(letter) = 62 - position',
            'method' => 'Reverse logic with high baseline. A is high, Z is lower.',
            'example' => 'A=61, B=60, ... Z=36',
        ],
        'clock_gematria' => [
            'short' => '12-cycle',
            'formula' => 'Values wrap modulo 12',
            'method' => 'A..L = 1..12, then repeats at M.',
            'example' => 'A=1, L=12, M=1, N=2',
        ],
        'reverse_clock_gematria' => [
            'short' => 'Reverse 12-cycle',
            'formula' => 'Reversed clock mapping',
            'method' => '12-cycle in inverted order according to the reference.',
            'example' => 'A=2, B=1, C=12, ...',
        ],
        'system9_gematria' => [
            'short' => '9-system',
            'formula' => 'Value(letter) = position * 9',
            'method' => 'Linear scaling by factor 9; same relations as Simple but amplified.',
            'example' => 'A=9, B=18, ... Z=234',
        ],
        'francis_bacon_gematria' => [
            'short' => 'Ordinal + 26',
            'formula' => 'Value(letter) = Position(A1..Z26) + 26',
            'method' => 'Simple offset system commonly used as Francis Bacon cipher.',
            'example' => 'A=27, B=28, ... Z=52',
        ],
        'septenary_gematria' => [
            'short' => 'Symmetric 1-7 wave',
            'formula' => 'A=1..G=7, then mirrored down to M=1 and back up to T=7, ending Z=1',
            'method' => 'Non-linear mirrored sequence that emphasizes central symmetry in words.',
            'example' => 'A=1, G=7, M=1, N=1, T=7, Z=1',
        ],
        'glyph_geometry_gematria' => [
            'short' => 'Letter shape complexity',
            'formula' => 'Value(letter) = 2x(lines) + 3x(curves) + 5x(enclosed_areas)',
            'method' => 'Approximates visual effort to draw uppercase glyphs, combining strokes and enclosed counters.',
            'example' => 'A=11 (3 lines + 1 enclosed area), O=8 (1 curve + 1 enclosed area)',
        ],
    ],
    'icons' => [
        'english_gematria' => 'fa-solid fa-language',
        'simple_gematria' => 'fa-solid fa-sort-numeric-up',
        'unknown_gematria' => 'fa-solid fa-mask',
        'pythagoras_gematria' => 'fa-solid fa-shapes',
        'jewish_gematria' => 'fa-solid fa-scroll',
        'prime_gematria' => 'fa-solid fa-hashtag',
        'reverse_satanic_gematria' => 'fa-solid fa-arrows-rotate',
        'clock_gematria' => 'fa-regular fa-clock',
        'reverse_clock_gematria' => 'fa-solid fa-clock-rotate-left',
        'system9_gematria' => 'fa-solid fa-grid-3x3',
        'francis_bacon_gematria' => 'fa-solid fa-scale-balanced',
        'septenary_gematria' => 'fa-solid fa-wave-square',
        'glyph_geometry_gematria' => 'fa-solid fa-draw-polygon',
    ],
    'themes' => [
        'technology' => 'Technology',
        'science' => 'Science',
        'finance' => 'Finance',
        'spirituality' => 'Spirituality',
        'culture' => 'Culture',
    ],
    'theme_keywords' => [
        'technology' => ['code', 'computer', 'ai', 'data', 'network', 'matrix', 'software', 'algorithm'],
        'science' => ['quantum', 'physics', 'biology', 'chemistry', 'energy', 'atom', 'genome', 'research'],
        'finance' => ['money', 'market', 'bank', 'crypto', 'stock', 'wealth', 'dollar', 'trade'],
        'spirituality' => ['god', 'soul', 'angel', 'spirit', 'prayer', 'sacred', 'ritual', 'mystic'],
        'culture' => ['music', 'film', 'art', 'history', 'myth', 'symbol', 'language', 'poetry'],
    ],
];
