<?php

return [
    'default_sources' => [
        ['name' => 'Reuters World', 'base_url' => 'https://www.reuters.com', 'rss_url' => 'https://feeds.reuters.com/Reuters/worldNews', 'locale' => 'en'],
        ['name' => 'Reuters US', 'base_url' => 'https://www.reuters.com', 'rss_url' => 'https://feeds.reuters.com/Reuters/domesticNews', 'locale' => 'en'],
        ['name' => 'Reuters Business', 'base_url' => 'https://www.reuters.com', 'rss_url' => 'https://feeds.reuters.com/reuters/businessNews', 'locale' => 'en'],
        ['name' => 'Reuters Technology', 'base_url' => 'https://www.reuters.com', 'rss_url' => 'https://feeds.reuters.com/reuters/technologyNews', 'locale' => 'en'],

        ['name' => 'BBC World', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/world/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC UK', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/uk/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Business', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/business/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Technology', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/technology/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Science', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/science_and_environment/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Health', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/health/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Politics', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/politics/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC Entertainment', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml', 'locale' => 'en'],
        ['name' => 'BBC US/Canada', 'base_url' => 'https://www.bbc.com', 'rss_url' => 'http://feeds.bbci.co.uk/news/world/us_and_canada/rss.xml', 'locale' => 'en'],

        ['name' => 'The Guardian World', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/world/rss', 'locale' => 'en'],
        ['name' => 'The Guardian UK', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/uk-news/rss', 'locale' => 'en'],
        ['name' => 'The Guardian US', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/us-news/rss', 'locale' => 'en'],
        ['name' => 'The Guardian Business', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/business/rss', 'locale' => 'en'],
        ['name' => 'The Guardian Technology', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/uk/technology/rss', 'locale' => 'en'],
        ['name' => 'The Guardian Science', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/science/rss', 'locale' => 'en'],
        ['name' => 'The Guardian Environment', 'base_url' => 'https://www.theguardian.com', 'rss_url' => 'https://www.theguardian.com/environment/rss', 'locale' => 'en'],

        ['name' => 'NYTimes Home', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml', 'locale' => 'en'],
        ['name' => 'NYTimes World', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/World.xml', 'locale' => 'en'],
        ['name' => 'NYTimes US', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/US.xml', 'locale' => 'en'],
        ['name' => 'NYTimes Business', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml', 'locale' => 'en'],
        ['name' => 'NYTimes Technology', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml', 'locale' => 'en'],
        ['name' => 'NYTimes Science', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/Science.xml', 'locale' => 'en'],
        ['name' => 'NYTimes Health', 'base_url' => 'https://www.nytimes.com', 'rss_url' => 'https://rss.nytimes.com/services/xml/rss/nyt/Health.xml', 'locale' => 'en'],

        ['name' => 'Washington Post World', 'base_url' => 'https://www.washingtonpost.com', 'rss_url' => 'https://feeds.washingtonpost.com/rss/world', 'locale' => 'en'],
        ['name' => 'Washington Post Politics', 'base_url' => 'https://www.washingtonpost.com', 'rss_url' => 'https://feeds.washingtonpost.com/rss/politics', 'locale' => 'en'],
        ['name' => 'WSJ World', 'base_url' => 'https://www.wsj.com', 'rss_url' => 'https://feeds.a.dj.com/rss/RSSWorldNews.xml', 'locale' => 'en'],
        ['name' => 'WSJ US Business', 'base_url' => 'https://www.wsj.com', 'rss_url' => 'https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml', 'locale' => 'en'],
        ['name' => 'Financial Times World', 'base_url' => 'https://www.ft.com', 'rss_url' => 'https://www.ft.com/world?format=rss', 'locale' => 'en'],
        ['name' => 'Financial Times Companies', 'base_url' => 'https://www.ft.com', 'rss_url' => 'https://www.ft.com/companies?format=rss', 'locale' => 'en'],
        ['name' => 'Al Jazeera', 'base_url' => 'https://www.aljazeera.com', 'rss_url' => 'https://www.aljazeera.com/xml/rss/all.xml', 'locale' => 'en'],
        ['name' => 'DW Top Stories', 'base_url' => 'https://www.dw.com', 'rss_url' => 'https://rss.dw.com/rdf/rss-en-all', 'locale' => 'en'],
        ['name' => 'France24', 'base_url' => 'https://www.france24.com', 'rss_url' => 'https://www.france24.com/en/rss', 'locale' => 'en'],
        ['name' => 'NHK World', 'base_url' => 'https://www3.nhk.or.jp', 'rss_url' => 'https://www3.nhk.or.jp/rss/news/cat0.xml', 'locale' => 'en'],
        ['name' => 'Sky News', 'base_url' => 'https://news.sky.com', 'rss_url' => 'https://feeds.skynews.com/feeds/rss/home.xml', 'locale' => 'en'],
        ['name' => 'CBC Top Stories', 'base_url' => 'https://www.cbc.ca', 'rss_url' => 'https://www.cbc.ca/webfeed/rss/rss-topstories', 'locale' => 'en'],
        ['name' => 'ABC Australia', 'base_url' => 'https://www.abc.net.au', 'rss_url' => 'https://www.abc.net.au/news/feed/51120/rss.xml', 'locale' => 'en'],

        ['name' => 'AP Top News', 'base_url' => 'https://apnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:apnews.com+top+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'AP World', 'base_url' => 'https://apnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:apnews.com+world+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'AP Politics', 'base_url' => 'https://apnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:apnews.com+politics+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'AP Business', 'base_url' => 'https://apnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:apnews.com+business+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Bloomberg', 'base_url' => 'https://www.bloomberg.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:bloomberg.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'CNBC', 'base_url' => 'https://www.cnbc.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:cnbc.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'CNN', 'base_url' => 'https://www.cnn.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:cnn.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'NPR', 'base_url' => 'https://www.npr.org', 'rss_url' => 'https://news.google.com/rss/search?q=site:npr.org+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'POLITICO', 'base_url' => 'https://www.politico.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:politico.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'The Economist', 'base_url' => 'https://www.economist.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:economist.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],

        // English-language Jewish / Israel-focused outlets
        ['name' => 'The Algemeiner', 'base_url' => 'https://www.algemeiner.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:algemeiner.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Times of Israel', 'base_url' => 'https://www.timesofisrael.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:timesofisrael.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Jerusalem Post', 'base_url' => 'https://www.jpost.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:jpost.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Jewish News UK', 'base_url' => 'https://www.jewishnews.co.uk', 'rss_url' => 'https://news.google.com/rss/search?q=site:jewishnews.co.uk+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Jewish Telegraphic Agency', 'base_url' => 'https://www.jta.org', 'rss_url' => 'https://news.google.com/rss/search?q=site:jta.org+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'The Forward', 'base_url' => 'https://forward.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:forward.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Jewish News Syndicate', 'base_url' => 'https://www.jns.org', 'rss_url' => 'https://news.google.com/rss/search?q=site:jns.org+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Haaretz English', 'base_url' => 'https://www.haaretz.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:haaretz.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Ynetnews', 'base_url' => 'https://www.ynetnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:ynetnews.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Israel Hayom English', 'base_url' => 'https://www.israelhayom.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:israelhayom.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Arutz Sheva', 'base_url' => 'https://www.israelnationalnews.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:israelnationalnews.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
        ['name' => 'Jewish Journal', 'base_url' => 'https://jewishjournal.com', 'rss_url' => 'https://news.google.com/rss/search?q=site:jewishjournal.com+when:1d&hl=en-US&gl=US&ceid=US:en', 'locale' => 'en'],
    ],
];
